---
- name: Install and Configure Sidecar on Debian based systems
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Install sidecar
      ansible.builtin.include_tasks:
        file: debian/install-sidecar.yml


- name: Install and Configure Sidecar on RPM based systems
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  when: ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Install sidecar
      ansible.builtin.include_tasks:
        file: rocky/install-sidecar.yml


- name: Install and Configure Sidecar on Windows
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ ansible_user }}@{{ adserver_domain }}"
  when: ansible_facts['os_family'] == 'Windows'
  block:
    - name: Configure sidecar
      ansible.builtin.include_tasks:
        file: windows/install-sidecar.yml
