---
# ----------------- FETCH USER INFO & CREATE API TOKEN -----------------
- name: Fetch users from Graylog API
  ansible.builtin.uri:
    url: "{{ SERVER_API_URL }}/users"
    method: GET
    headers: &common_headers
      Authorization: "Basic {{ (SERVER_API_USERNAME + ':' + SERVER_API_PASSWORD) | b64encode }}"
      X-Requested-By: "Ansible"
      Accept: "application/json"
      Content-Type: "application/json"
    return_content: true
  register: user_response

- name: Extract user ID
  ansible.builtin.set_fact:
    user_id: "{{ user_response.json.users | selectattr('username', 'equalto', SERVER_API_USERNAME) | map(attribute='id') | first }}"

- name: Create new API token for the user
  ansible.builtin.uri:
    url: "{{ SERVER_API_URL }}/users/{{ user_id }}/tokens/{{ NEW_TOKEN_NAME }}"
    method: POST
    headers: *common_headers
    return_content: true
  register: token_response

- name: Store API token
  ansible.builtin.set_fact:
    SERVER_API_TOKEN: "{{ token_response.json.token }}"
