cluster:
  children:
    ctrl_plane:
      vars:
        discord_webhook_url:
          0: 'https://discord.com/api/webhooks/0123456789/abcdefghijklmnopqrstuvwxyz'
    node_1:
    node_2:
    node_3:

worker_nodes:
  children:
    node_1:
    node_2:
    node_3:

linux:
  children:
    ctrl_plane:
    database:
    graylog:
    nginx:
    node_1:
    node_2:
    node_3:
  vars:
    ansible_user: black-team
    ansible_private_key_file: ../../../../documentation/black_team/black-team
    ansible_port: 22

graylog_clients:
  children:
    node_1:
    node_3:
    windows_ca:
    windows_workstation:

graylog:
  vars:
    ansible_user: admin
    ansible_private_key_file: ../../../../documentation/black_team/black-team
    ansible_port: 22

scorestack:
  hosts:
    score.placebo-pharma.com
  vars:
    ansible_user: ubuntu
    ansible_private_key_file: ../documentation/black_team/black-team

wireguard:
  hosts:
    vpn.placebo-pharma.com
  vars:
    ansible_user: ubuntu
    ansible_private_key_file: ../../../documentation/black_team/black-team

windows:
  children:
    windows_ca:
    windows_dc:
    windows_workstation:
  vars:
    ansible_user: Administrator
    ansible_password: "{{ adserver_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ntp_servers: "0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org"
    netbios: "PLACEBO-PHARMA"
    public_dns_forwarders:
      - "8.8.8.8"
      - "1.1.1.1"

windows_clients:
  children:
    windows_ca:
    windows_workstation:

all:
  vars:
    domain: placebo-pharma.com
    adserver_domain: placebo-pharma.local
    adserver_password: example-password
    blackteam_password: example-password
    team_address:
      firewall_public: "10.255.{{ team }}.254"
      firewall_private: "10.0.{{ (team * 4) + 3 }}.254"
      firewall_dmz: "10.0.{{ (team * 4) }}.254"
      ctrl_plane: "10.0.{{ (team * 4) + 2 }}.255"
      database: "10.0.{{ (team * 4) + 3 }}.192"
      graylog: "10.0.{{ (team * 4) }}.247"
      nginx: "10.0.{{ (team * 4) }}.200"
      node_1: "10.0.{{ (team * 4) + 3 }}.0"
      node_2: "10.0.{{ (team * 4) + 3 }}.77"
      node_3: "10.0.{{ (team * 4) + 2 }}.5"
      windows_ca: "10.0.{{ (team * 4) }}.138"
      windows_dc: "10.0.{{ (team * 4) + 2 }}.77"
      windows_workstation: "10.0.{{ (team * 4) + 2 }}.128"
