---
- name: Ensure firewalld is installed
  ansible.builtin.yum:
    name: firewalld
    state: present
  tags:
    - firewall

- name: Ensure firewalld is running and enabled on boot
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  tags:
    - firewall

- name: Add firewalld tcp rules for multiple ports
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 22
    - 443
    - 993
    - 1337
    - 5901
    - 8080
    - 8086
    - 8443
  tags:
    - firewall

- name: Add firewalld udp rules for multiple ports
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 53
    - 993
  tags:
    - firewall

- name: Reload firewalld to apply changes
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  tags:
    - firewall
