---
- name: Copy teleport configuration template
  ansible.builtin.template:
    src: templates/teleport.yaml.j2
    dest: /etc/teleport.yaml
    mode: '0664'
    owner: root
    group: root
  tags:
    - teleport

- name: Start and enable Teleport
  ansible.builtin.service:
    name: teleport
    state: restarted
    enabled: true
  tags:
    - teleport
