---
- name: Domain creation
  hosts: "{{ ansible_limit | default('windows_dc') }}"
  gather_facts: true
  gather_subset: "!all,system"
  vars_files:
    - "../../team_common.yaml"

  tasks:
    - name: Include AWS SAC Role
      ansible.builtin.include_role:
        name: aws.sac

    - name: Include Base Windows Role
      ansible.builtin.include_role:
        name: base_win
      vars:
        set_hostname: "{{ hostname }}"
        dns_servers: "{{ team_address.windows_dc }}"
        ntp_resync: true

    - name: Establish New Active Directory Domain
      microsoft.ad.domain:
        dns_domain_name: "{{ adserver_domain }}"
        safe_mode_password: "{{ ansible_password }}"
        reboot: false
      register: domain_create

    - name: Reboot host if install requires it
      ansible.windows.win_reboot:
      when: domain_create.reboot_required

    - name: Create black-team user
      microsoft.ad.user:
        name: black-team
        firstname: Black
        lastname: Team
        display_name: Black Team
        description: DO NOT TOUCH THIS ACCOUNT
        sam_account_name: black-team
        upn: "black-team@{{ adserver_domain }}"
        password: "{{ blackteam_password }}"
        groups:
          set:
          - Domain Admins
          - Domain Users
          - Enterprise Admins
        state: present
      register: domain_create_user_result
      retries: 30
      delay: 15
      until: domain_create_user_result is successful

    - name: Create ssm-user user
      microsoft.ad.user:
        name: ssm-user
        firstname: SSM
        lastname: User
        display_name: SSM User
        description: DO NOT TOUCH THIS ACCOUNT
        sam_account_name: ssm-user
        upn: "ssm-user@{{ adserver_domain }}"
        password: "{{ blackteam_password }}"
        groups:
          set:
          - Domain Admins
          - Domain Users
        state: present