---
- name: Deploy Nginx
  hosts: scorestack
  gather_facts: false
  become: true
  vars_files:
    - ../vars/score.yml
  tasks:
    - name: Install Nginx package
      ansible.builtin.package:
        name: nginx
        state: latest

    - name: Remove sites-default
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy TLS files
      block:
        - name: Create SSL directory
          ansible.builtin.file:
            path: /etc/nginx/ssl
            state: directory
            mode: '0755'

        - name: Copy TLS certificate
          ansible.builtin.copy:
            src: ../../documentation/black_team/certificates/scorestack/cert.crt
            dest: /etc/nginx/ssl/score.{{ base_domain }}.crt
            mode: '0644'

        - name: Copy TLS key
          ansible.builtin.copy:
            src: ../../documentation/black_team/certificates/scorestack/private.key
            dest: /etc/nginx/ssl/score.{{ base_domain }}.key
            mode: '0644'

    - name: Configure Nginx
      ansible.builtin.copy:
        src: ../files/nginx/
        dest: /etc/nginx/
      notify:
        - Restart Nginx

    - name: Grafana dashboard configmap
      ansible.builtin.template:
        src: "../templates/scorestack.conf.j2"
        dest: "/etc/nginx/sites-enabled/scorestack.conf"
        mode: '0644'

    - name: Enable Nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true

  handlers:
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
