---
- name: Configure Graylog agents
  hosts: graylog_clients
  gather_facts: true

  vars:
    SERVER_API_URL: "http://{{ team_address.graylog }}:9000/api"
    SERVER_API_USERNAME: "admin" 
    SERVER_API_PASSWORD: "example-password"
    NEW_TOKEN_NAME: "sidecar"

  pre_tasks:
    - name: Fetch token for sidecar install
      ansible.builtin.include_tasks: tasks/fetch_token.yaml
      args:
        apply:
          delegate_to: localhost
          tags: token
      tags: token

    - name: Set sidecar configurations on graylog
      ansible.builtin.include_tasks: tasks/configure_sidecar.yaml
      args:
        apply:
          delegate_to: localhost
          tags: config
      run_once: true
      tags: config

  tasks:
    - name: Install graylog clients
      ansible.builtin.include_role:
        name: install_client
      tags: install
