---
- name: Gather facts
  ansible.builtin.setup:

- name: Set enabled variable only if running on Amazon EC2
  ansible.builtin.set_fact:
    is_aws: true
  when:
    - ansible_system_vendor is defined
    - ansible_system_vendor == "Amazon EC2"

- name: Include enabled tasks
  ansible.builtin.include_tasks: enabled.yaml
  when:
    - is_aws | default(false)
    - state == "present"

- name: Include disabled tasks
  ansible.builtin.include_tasks: disabled.yaml
  when:
    - is_aws | default(false)
    - state == "absent"