#TODO: #31 Cleanup copied files on DC & Clear logs of powershell and ansible
---
- name: Automated Setup of Active Directory Users and Groups
  hosts: "{{ ansible_limit | default('windows_dc') }}"
  gather_facts: false
  vars:
    ansible_user: "administrator@{{ ad.domain }}"

  tasks:
    - name: Include bginfo role
      ansible.builtin.include_role:
        name: bginfo

    - name: Include populate.users role
      ansible.builtin.include_role:
        name: populate.users
      vars:
        users_source_csv: "../files/users/users.csv"

    - name: Include populate.users role for former employees
      ansible.builtin.include_role:
        name: populate.users
      vars:
        users_source_csv: "../files/users/former_employees.csv"

    - name: Include populate.gpo role
      ansible.builtin.include_role:
        name: populate.gpo
      vars:
        gpo_source: "../files/gpo/"
        gpo_definitions: "../files/gpo/definitions.yaml"
        gpo_fake_names: true

    - name: Create sshd user
      microsoft.ad.user:
        name: sshd
        firstname: sshd
        sam_account_name: sshd
        upn: "sshd@{{ ad.domain }}"
        password: "example-password"
        groups:
          set:
          - Domain Users
        state: present
