---
- name: Join clients to Active Directory Domain
  hosts: windows_domain_join
  gather_facts: true
  tasks:
    - name: Include AWS SAC Role
      ansible.builtin.include_role:
        name: aws.sac

    - name: Include Base Windows Role
      ansible.builtin.include_role:
        name: base.win
      vars:
        set_hostname: "{{ hostname }}"
        dns_servers: "{{ team_address.windows_dc }}"
        ntp_resync: true

    - name: Join Object to Active Directory Domain
      microsoft.ad.membership:
       hostname: "{{ hostname }}"
       dns_domain_name: "{{ ad.domain }}"
       domain_admin_user: "{{ ansible_user }}@{{ ad.domain }}"
       domain_admin_password: "{{ ansible_password }}"
       reboot: true
       reboot_timeout: 600
       state: domain

- name: Promote DC-02 to Domain Controller
  hosts: windows_dc_2
  gather_facts: false
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}@{{ ad.domain }}"
    ansible_become_password: "{{ ansible_password }}"
  tasks:
    - name: Ensure a server is a domain controller
      microsoft.ad.domain_controller:
        dns_domain_name: "{{ ad.domain }}"
        domain_admin_user: "{{ ansible_user }}@{{ ad.domain }}"
        domain_admin_password: "{{ ansible_password }}"
        safe_mode_password: "{{ ansible_password }}"
        install_dns: true
        state: domain_controller
        reboot: true
        reboot_timeout: 600

- name: Setup Windows CA
  hosts: windows_ca
  gather_facts: false
  vars:
    ansible_user: "Administrator@{{ ad.domain }}"
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "Administrator@{{ ad.domain }}"
    ansible_become_password: "{{ ansible_password }}"
  tasks:
    
    - name: Configure Windows CA
      ansible.builtin.include_role:
        name: adcs
      vars:
        ca_backup_source: "../files/ca/placebo-pharma-CA-01-CA.p12"
        domain: "{{ ad.domain }}"
        domain_username: "Administrator@{{ ad.domain }}"
        domain_password: "{{ ansible_password }}"
        ca_common_name: "{{ad.netbios}}-CA"
        ca_web_enrollment: true
