- name: Configure DNS on Domain Controllers
  hosts: windows_domain_controllers
  gather_facts: false
  vars:
    ansible_user: "Administrator@{{ ad.domain }}"
  tasks:
    - name: Set DNS Forwarders on Domain Controllers
      ansible.builtin.include_role:
        name: dns.forwarder
      vars:
        dns_forwarders: "{{ team_address.firewall_corp }}"

    - name: Set DC-01 Client DNS Servers
      ansible.windows.win_dns_client:
        adapter_names: "*"
        dns_servers:
          - "{{ team_address.windows_dc }}"
          - "{{ team_address.windows_dc_2 }}"
      when: "'dc-01' in hostname"

    - name: Set DC-02 Client DNS Servers
      ansible.windows.win_dns_client:
        adapter_names: "*"
        dns_servers:
          - "{{ team_address.windows_dc_2 }}"
          - "{{ team_address.windows_dc }}"
      when: "'dc-02' in hostname"

- name: Configure DNS on Workstations
  hosts: windows_clients
  gather_facts: false
  vars:
    ansible_user: "Administrator@{{ ad.domain }}"
  tasks:
    - name: Set DNS Servers on Workstations
      ansible.windows.win_dns_client:
        adapter_names: "*"
        dns_servers:
          - "{{ team_address.windows_dc }}"
          - "{{ team_address.windows_dc_2 }}"

- name: Setup BGInfo on Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Include BGInfo Role
      ansible.builtin.include_role:
        name: bginfo.local