customRules:
  rules-exclusions.yaml: |-
    - list: expected_udp_ports
      items: [53, 8500, 8501, 8502, 8503, openvpn_udp_ports, l2tp_udp_ports, statsd_ports, ntp_ports, test_connect_ports]
    - list: user_known_change_thread_namespace_binaries
      items: [crio, multus, nsenter, containerd-shim, longhorn-manage]
    - list: allowed_container_images_loading_kernel_module
      items: [docker.io/longhornio/longhorn-instance-manager]
    - macro: user_known_package_manager_in_container
      condition: proc.cmdline="dpkg -l"
    - macro: user_known_network_tool_activities
      condition: (proc.name = "nc" and (container.image.repository = "docker.io/longhornio/longhorn-instance-manager" or container.image.repository = "longhornio/longhorn-instance-manager"))
    - macro: user_known_contact_k8s_api_server_activities
      condition: >
        (container.name = "grafana-sc-dashboard" and k8s.ns.name = "monitoring" and container.image.repository = "quay.io/kiwigrid/k8s-sidecar" and proc.cmdline = "python -u /app/sidecar.py" and user.uid = "472") or
        (container.name = "grafana-sc-datasources" and k8s.ns.name = "monitoring" and container.image.repository = "quay.io/kiwigrid/k8s-sidecar" and proc.cmdline = "python -u /app/sidecar.py" and user.uid = "472") or
        (container.name = "kube-state-metrics" and k8s.ns.name = "monitoring" and container.image.repository = "registry.k8s.io/kube-state-metrics/kube-state-metrics" and proc.exepath = "/kube-state-metrics" and user.uid = "65534") or
        (container.name = "host" and container.id = "host" and proc.pname = "systemd" and proc.exepath = "/usr/lib/systemd/systemd-executor")
    - macro: user_known_shell_config_modifiers
      condition: >
        (container.name = "host" and container.id = "host" and proc.pname = "crio" and proc.exepath = "/usr/bin/crio" and user.name = "root") or
        (container.name = "host" and container.id = "host" and proc.pname = "systemd" and proc.cmdline = "containerd") or
        (container.name = "host" and container.id = "host" and proc.pname = "dockerd")
    - macro: user_known_read_sensitive_files_activities
      condition: >
        (container.name = "host" and container.id = "host" and proc.pname = "systemd" and proc.exepath = "/usr/lib/systemd/systemd-executor") or
        (container.name = "host" and container.id = "host" and proc.pname = "graylog-sidecar" and proc.exepath = "/usr/lib/graylog-sidecar/auditbeat" and user.name = "root")
    - macro: user_known_mount_in_privileged_containers
      condition: >
        (container.name = "longhorn-csi-plugin" and k8s.ns.name = "infrastructure" and container.image.repository = "docker.io/longhornio/longhorn-instance-manager" and proc.exepath = "/usr/bin/mount") or
        (container.name = "instance-manager" and k8s.ns.name = "infrastructure" and container.image.repository = "docker.io/longhornio/longhorn-instance-manager" and proc.exepath = "/usr/bin/mount") or
        (k8s.ns.name = "infrastructure" and container.image.repository = "longhornio/longhorn-manager" and proc.exepath = "/usr/bin/mount")
    - macro: allowed_clear_log_files
      condition: >
        (container.name = "instance-manager" and k8s.ns.name = "infrastructure" and container.image.repository = "docker.io/longhornio/longhorn-instance-manager")
    - rule: Super Sensitive File Read
      desc: Secret file was accessed by an unauthorized process
      condition: open_read and fd.name = "/secrets.txt"
      output: A secret file was read (file=%fd.name pcmdline=%proc.pcmdline evt_type=%evt.type user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline terminal=%proc.tty)
      priority: WARNING
      tags: [custom]
