---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: open-emr
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: root
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: open-emr
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          args:
            - mysqld
            - --character-set-server=utf8mb4
          image: mariadb:10.6
          ports:
            - containerPort: 3306
              name: mysql-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "1"
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/mysql/
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-config
          emptyDir: {}
        - name: initdb
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 6Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: open-emr
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql-port
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
---
apiVersion: v1
kind: Service
metadata:
  name: tmp-debug-mysql
  namespace: open-emr
spec:
  type: NodePort
  ports:
    - name: mysql-port
      port: 3306
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
