---
apiVersion: v1
kind: Secret
metadata:
  name: openemr-credentials
  namespace: open-emr
stringData:
  MYSQL_USER: openemr
  MYSQL_PASS: openemr
  OE_USER: admin
  OE_PASS: pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: openemr
  name: openemr
  namespace: open-emr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openemr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: openemr
    spec:
      automountServiceAccountToken: false
      containers:
        - name: openemr
          image: openemr/openemr:7.0.2
          env:
            - name: MYSQL_HOST
              value: "mysql.open-emr.svc.cluster.local"
            - name: MYSQL_ROOT_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
          envFrom:
            - secretRef:
                name: openemr-credentials
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            limits:
              cpu: 1000m
              memory: 1G
              ephemeral-storage: 5Gi
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: openemr
  name: openemr
  namespace: open-emr
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
  selector:
    name: openemr
