providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
  kubernetesCRD:
    ingressClass: traefik
externalTrafficPolicy: Local
metrics:
  prometheus:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
ingressRoute:
  dashboard:
    enabled: true
logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json
deployment:
  replicas: 4
service:
  enabled: true
  type: NodePort
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
ports:
  mysql:
    expose:
      default: true
    exposedPort: 3306
    nodePort: 30336
    port: 3306
    protocol: TCP
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443
gateway:
  namespacePolicy: All
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
