---
- name: Install and Configure MongoDB, Graylog Data Node, and Graylog Server
  hosts: graylog
  become: true
  vars:
    former_employees_data: "{{ lookup('file', '../../../../documentation/employee_data/former_employees.yaml') | from_yaml }}"
    users_data: "{{ lookup('file', '../../../../documentation/employee_data/employees.yaml') | from_yaml }}"
    team_number: "{{ hostvars[inventory_hostname]['team'] }}"
  tasks:
    - name: Update admin password
      ansible.builtin.user:
        name: admin
        password: "{{ 'example-password' | password_hash('sha512') }}"
      tags:
        - password

    - name: Copy private IP template (Lazy developers... SMH)
      ansible.builtin.template:
        src: templates/graylog-server.conf
        dest: /etc/graylog/server/server.conf
        owner: root
        group: root
        mode: '0644'
      vars:
        private_server_ip: "10.0.{{ team_number }}.169"
      tags:
        - config

    - name: Restart Graylog
      ansible.builtin.service:
        name: graylog-server
        state: restarted
        enabled: true
      tags:
        - config

    - name: Pause for a minute to let Graylog catch up
      ansible.builtin.pause:
        minutes: 1

    - name: Install Teleport
      ansible.builtin.include_tasks:
        file: "tasks/teleport.yaml"
      vars:
        join_token: 1KSP55J35U9O5YQC92PEZ594
        teleport_server_dns_address: teleport.{{ team_number }}.placebo-pharma.com
      tags:
        - teleport

    - name: Include install role if install var is present
      ansible.builtin.include_role:
        name: graylog
      vars:
        graylog_install: false
        graylog_configure: true

- name: Setup Graylog Configurations
  hosts: graylog
  become: true
  vars_files:
    - ../../../shared/graylog/vars/main.yml
  vars:
    former_employees_data: "{{ lookup('file', '../../../../documentation/employee_data/former_employees.yaml') | from_yaml }}"
    users_data: "{{ lookup('file', '../../../../documentation/employee_data/employees.yaml') | from_yaml }}"
  tasks:
    - name: Pause for a minute to let Graylog catch up
      ansible.builtin.pause:
        minutes: 1

    - name: Setup Graylog Users
      ansible.builtin.include_tasks:
        file: tasks/graylog_users.yaml
