#https://github.com/rolehippie/graylog-sidecar/blob/master/tasks/main.yml
---
- name: Install required package
  ansible.builtin.apt:
    deb: "https://github.com/Graylog2/collector-sidecar/releases/download/1.5.0/graylog-sidecar_1.5.0-1_amd64.deb"
    state: present

- name: Template the sidecar configuration
  ansible.builtin.template:
    src: templates/linux_sidecar.yml.j2
    dest: /etc/graylog/sidecar/sidecar.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - Restart linux-graylog-sidecar

- name: Write service file
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/graylog-sidecar.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - Restart linux-graylog-sidecar

- name: Start graylog-sidecar service
  ansible.builtin.systemd:
    name: graylog-sidecar
    state: started
    daemon_reload: true
    masked: false
    enabled: true
