---
- name: Join CA to Active Directory Domain
  hosts: windows_ca
  gather_facts: true
  tasks:
    - name: Include AWS SAC Role
      ansible.builtin.include_role:
        name: aws.sac

    - name: Include Base Windows Role
      ansible.builtin.include_role:
        name: base.win
      vars:
        set_hostname: "{{ hostname }}"
        dns_servers: "{{ team_address.firewall_corp }}"
        ntp_resync: true

    - name: Join Object to Active Directory Domain
      microsoft.ad.membership:
       hostname: "{{ hostname }}"
       dns_domain_name: "{{ ad.domain }}"
       domain_admin_user: "{{ ansible_user }}@{{ ad.domain }}"
       domain_admin_password: "{{ ansible_password }}"
       reboot: true
       reboot_timeout: 600
       state: domain

- name: Setup Windows CA
  hosts: windows_ca
  gather_facts: false
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}@{{ ad.domain }}"
    ansible_become_password: "{{ ansible_password }}"
  tasks:
    - name: Configure Windows CA
      ansible.builtin.include_role:
        name: ca
      vars:
        ca_backup_source: "../files/ca/placebo-pharma-CA-01-CA.p12"
        ca_backup_password: "{{ ansible_password }}"