---
- name: Join DC-02 to Active Directory Domain
  hosts: windows_dc_2
  gather_facts: true
  tasks:
    - name: Include AWS SAC Role
      ansible.builtin.include_role:
        name: aws.sac

    - name: Include Base Windows Role
      ansible.builtin.include_role:
        name: base.win
      vars:
        set_hostname: "{{ hostname }}"
        dns_servers: "{{ team_address.windows_dc }}"
        ntp_resync: true

    - name: Join Object to Active Directory Domain
      microsoft.ad.membership:
       hostname: "{{ hostname }}"
       dns_domain_name: "{{ ad.domain }}"
       domain_admin_user: "{{ ansible_user }}@{{ ad.domain }}"
       domain_admin_password: "{{ ansible_password }}"
       reboot: true
       reboot_timeout: 600
       state: domain
      register: domain_join_result
      retries: 4
      delay: 5
      until: domain_join_result is successful

- name: Promote DC-02 to Domain Controller
  hosts: windows_dc_2
  gather_facts: false
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}@{{ ad.domain }}"
    ansible_become_password: "{{ ansible_password }}"
  tasks:
    - name: Ensure a server is a domain controller
      microsoft.ad.domain_controller:
        dns_domain_name: "{{ ad.domain }}"
        domain_admin_user: "{{ ansible_user }}@{{ ad.domain }}"
        domain_admin_password: "{{ ansible_password }}"
        safe_mode_password: "{{ ansible_password }}"
        install_dns: true
        state: domain_controller
        reboot: true
        reboot_timeout: 600