---
- name: Ensure /mount/longhorn directory exists
  ansible.builtin.file:
    path: /mount/longhorn
    state: directory
    mode: '0755'

- name: Check if /dev/sdb or /dev/nvme1n1 exists
  ansible.builtin.stat:
    path: /dev/sdb
  register: sdb_device

- name: Check if /dev/nvme1n1 exists if /dev/sdb does not
  ansible.builtin.stat:
    path: /dev/nvme1n1
  register: nvme_device
  when: not sdb_device.stat.exists

- name: Fail if neither /dev/sdb nor /dev/nvme1n1 exists
  ansible.builtin.fail:
    msg: "Neither /dev/sdb nor /dev/nvme1n1 exists"
  when: not sdb_device.stat.exists and not nvme_device.stat.exists

- name: Determine the device to use
  ansible.builtin.set_fact:
    device_to_use: "{{ '/dev/sdb' if sdb_device.stat.exists else '/dev/nvme1n1' }}"

- name: Check if the device is formatted
  ansible.builtin.command:
    cmd: lsblk -f {{ device_to_use }}
  register: device_format
  changed_when: false

- name: Format the device as ext4
  community.general.filesystem:
    fstype: ext4
    dev: "{{ device_to_use }}"
  when: device_format.stdout.find('ext4') == -1

- name: Mount the device to /mount/longhorn
  ansible.posix.mount:
    src: "{{ device_to_use }}"
    path: /mount/longhorn
    fstype: ext4
    state: mounted
