---
- name: Copy pipeline directory
  ansible.builtin.copy:
    src: templates/pipeline/
    dest: "/home/ubuntu/pipeline/"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
    directory_mode: '0755'
  tags:
    - pipeline

- name: Copy Falco rules values
  ansible.builtin.copy:
    src: templates/falco-rules.yaml
    dest: "/home/ubuntu/falco-rules.yaml"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  tags:
    - falco
