---
- name: Remove code init job
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: absent
    api_version: batch/v1
    kind: Job
    namespace: infrastructure
    name: code-init
  tags:
    - services
    - code

# https://hub.docker.com/r/linuxserver/code-server
- name: Create code server deployment
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: code
        namespace: infrastructure
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: code-server
        template:
          metadata:
            labels:
              app: code-server
          spec:
            serviceAccountName: code
            restartPolicy: Always
            containers:
              - name: code-server
                image: linuxserver/code-server:4.97.2
                ports:
                  - containerPort: 8443
                env:
                  - name: PUID
                    value: "0"
                  - name: PGID
                    value: "0"
                  - name: TZ
                    value: "Etc/UTC"
                  - name: DEFAULT_WORKSPACE
                    value: "/workspace"
                volumeMounts:
                  - name: workspace
                    mountPath: /workspace/
            dnsPolicy: "None"
            dnsConfig:
              nameservers:
                - 10.0.{{ team_number }}.254
            volumes:
              - name: workspace
                persistentVolumeClaim:
                  claimName: code
  tags:
    - services
    - code
