---
# https://longhorn.io
# https://artifacthub.io/packages/helm/longhorn/longhorn
- name: Deploy Longhorn
  become: true
  become_user: ubuntu
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: '1.8.0'
    release_namespace: infrastructure
    values:
      preUpgradeChecker:
        jobEnabled: false
      ingress:
        enabled: false
      defaultSettings:
        defaultDataPath: /mount/longhorn
      longhornUI:
        replicas: 1
      namespaceOverride: infrastructure
      metrics:
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
  tags:
    - services
    - longhorn

- name: Label the Longhorn frontend service
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: patched
    kind: Service
    name: longhorn-frontend
    namespace: infrastructure
    definition:
      metadata:
        annotations:
          teleport.dev/name: longhorn
          teleport.dev/port: '80'
        labels:
          teleport.dev/proxy: "true"
  tags:
    - services
    - longhorn

- name: Wait for Longhorn pods become ready
  become: true
  become_user: ubuntu
  ansible.builtin.shell:
    cmd: "kubectl wait --namespace=infrastructure --for=condition=Ready pods --selector app.kubernetes.io/instance=longhorn --timeout=180s"
  tags:
    - services
    - longhorn

- name: Create Longhorn http route
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: longhorn-http
        namespace: infrastructure
      spec:
        parentRefs:
          - name: traefik
            namespace: infrastructure
            sectionName: http
        hostnames:
          - "longhorn.{{ hostvars[inventory_hostname]['team'] }}.placebo-pharma.com"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: longhorn-frontend
                namespace: infrastructure
                port: 80
  tags:
    - services
    - longhorn

- name: Create Longhorn https route
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: longhorn-https
        namespace: infrastructure
      spec:
        parentRefs:
          - name: traefik
            namespace: infrastructure
            sectionName: https
        hostnames:
          - "longhorn.{{ hostvars[inventory_hostname]['team'] }}.placebo-pharma.com"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: longhorn-frontend
                namespace: infrastructure
                port: 80
  tags:
    - services
    - longhorn
