---
# https://goteleport.com/docs/enroll-resources/auto-discovery/kubernetes-applications/get-started/
# https://goteleport.com/docs/reference/helm-reference/teleport-kube-agent/
- name: Deploy teleport
  become: true
  become_user: ubuntu
  kubernetes.core.helm:
    name: teleport-agent
    chart_ref: teleport/teleport-kube-agent
    chart_version: "15.4.29"
    release_namespace: security
    timeout: 3m
    values:
      roles: kube,app,discovery
      authToken: STF5Y7KCA80S7IOHEPUNVB6SRMTX1U78 # Hardcoded token in teleport setup
      proxyAddr: teleport.{{ team_number }}.placebo-pharma.com:443
      kubeClusterName: PlaceboPharma
      labels:
        service: kubernetes
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.245.0.10
          - 10.0.{{ team_number }}.254
      kubernetesDiscovery:
        - types: ["app"]
          namespaces:
            ["pipeline", "security", "monitoring", "infrastructure"]
          labels:
            teleport.dev/proxy: true
      storage:
        enabled: true
        storageClassName: longhorn
  tags:
    - services
    - teleport
