---
- name: Create website service account
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: website
        namespace: web
  tags:
    - services
    - website


- name: Create website deployment
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: website
        namespace: web
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: website
        template:
          metadata:
            labels:
              app: website
          spec:
            serviceAccountName: website
            automountServiceAccountToken: false
            restartPolicy: Always
            containers:
              - name: website
                image: public.ecr.aws/abcdefg/placebo-pharma/website:latest
                ports:
                  - containerPort: 80
                env:
                  - name: TZ
                    value: "Etc/UTC"
  tags:
    - services
    - website

- name: Create website service
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: website
        namespace: web
      spec:
        selector:
          app: website
        ports:
          - port: 8080
            targetPort: 80
  tags:
    - services
    - website


- name: Create website http route
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: website-http
        namespace: web
      spec:
        parentRefs:
          - name: traefik
            namespace: infrastructure
            sectionName: http
        hostnames:
          - "{{ hostvars[inventory_hostname]['team'] }}.placebo-pharma.com"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: website
                namespace: web
                port: 8080
  tags:
    - services
    - website

- name: Create website https route
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: website-https
        namespace: web
      spec:
        parentRefs:
          - name: traefik
            namespace: infrastructure
            sectionName: https
        hostnames:
          - "{{ hostvars[inventory_hostname]['team'] }}.placebo-pharma.com"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: website
                namespace: web
                port: 8080
  tags:
    - services
    - website


- name: Create website network policy
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: website
        namespace: web
      spec:
        podSelector:
          matchLabels:
            app: website
        policyTypes:
          - Egress
        egress:
          - to:
              - namespaceSelector: {}
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              - port: 53
                protocol: UDP
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: infrastructure
            ports:
              - port: 80
              - port: 443
  tags:
    - services
    - website
