---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recorder
  namespace: pipeline
  labels:
    app.kubernetes.io/name: recorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: recorder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: recorder
    spec:
      serviceAccountName: recorder
      containers:
        - name: recorder
          image: public.ecr.aws/abcdefg/placebo-pharma/recorder:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
              ephemeral-storage: "50Mi"
              memory: 128Mi
            limits:
              cpu: 100m
              ephemeral-storage: "1Gi"
              memory: 256Mi
          envFrom:
            - secretRef:
                name: influxdb-credentials
            - configMapRef:
                name: recorder-config
