services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=server.py
      - LOG_LEVEL=DEBUG
      - INFLUX_URL=http://host.docker.internal:8086
      - INFLUXDB_TOKEN=zU8-j9sySK9NoFf73LAyopV56CIbGRXJ1hDzbOCDH6GjJs3NnFfUOBLVJBKG2ohW8HoseQggxKZg9gfOkSfkfQ==
      - INFLUX_ORG=PlaceboPharma
      - INFLUX_BUCKET=PlaceboPharmaData
    restart: unless-stopped
