---
- name: BCDEdit Set EMS on
  ansible.windows.win_command:
    cmd: bcdedit /ems {current} on
  when: enabled

- name: BCDEdit Set EMS baud rate
  ansible.windows.win_command:
    cmd: bcdedit /emssettings EMSPORT:1 EMSBAUDRATE:115200
  when: enabled

- name: BCDEdit Set EMS displaybootmenu
  ansible.windows.win_command:
    cmd: bcdedit /set {bootmgr} displaybootmenu yes
  when: enabled

- name: BCDEdit Set EMS timeout
  ansible.windows.win_command:
    cmd: bcdedit /set {bootmgr} timeout 15
  when: enabled

- name: BCDEdit Set EMS bootmgr
  ansible.windows.win_command:
    cmd: bcdedit /set {bootmgr} bootems yes
  when: enabled

