---
- name: Download the nerdctl archive
  ansible.builtin.get_url:
    url: "https://github.com/containerd/nerdctl/releases/download/v1.6.2/nerdctl-1.6.2-linux-amd64.tar.gz"
    dest: "/tmp/nerdctl.tar.gz"
    mode: "0600"

- name: Create a temporary directory
  ansible.builtin.file:
    path: "/tmp/nerdctl_extracted"
    state: directory
    mode: "0755"

- name: Extract Archive
  ansible.builtin.unarchive:
    src: "/tmp/nerdctl.tar.gz"
    dest: "/tmp/nerdctl_extracted"
    remote_src: true

- name: Copy File to Binary Location
  ansible.builtin.copy:
    src: "/tmp/nerdctl_extracted/nerdctl"
    dest: "/usr/bin/nerdctl"
    remote_src: true
    owner: root
    group: root
    mode: '0755'

- name: Remove the nerdctl archive
  ansible.builtin.file:
    path: "/tmp/nerdctl.tar.gz"
    state: absent

- name: Remove the nerdctl unarchived files
  ansible.builtin.file:
    path: "/tmp/nerdctl_extracted"
    state: absent

- name: Nerdctl completion
  block:
    - name: Install nerdctl bash completion
      ansible.builtin.command: nerdctl completion bash
      register: nerdctl_completion
      changed_when: false

    - name: Create nerdctl bash completion file
      ansible.builtin.copy:
        content: "{{ nerdctl_completion.stdout_lines | join('\n') }}"
        dest: /etc/bash_completion.d/nerdctl
        owner: root
        group: root
        mode: '0644'
