---
# https://github.com/jwillikers/ansible_fish/tree/main
- name: Install fish
  ansible.builtin.dnf:
    name: fish
    state: present
  tags:
    - fish

- name: Set fish as the user's login shell
  ansible.builtin.user:
    name: rocky
    shell: /usr/bin/fish
  register: u
  tags:
    - fish

- name: Create the user's fish config directory
  ansible.builtin.file:
    path: "{{ u.home }}/.config/fish/functions/"
    state: directory
    recurse: true
    mode: '0770'
    owner: rocky
  tags:
    - fish

- name: Disable the greeting message
  ansible.builtin.copy:
    src: templates/greeting.fish
    dest: "{{ u.home }}/.config/fish/functions/fish_greeting.fish"
    mode: '0640'
    owner: rocky
  tags:
    - fish

- name: Download fish prompt
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/oh-my-fish/theme-robbyrussell/refs/heads/master/functions/fish_prompt.fish'
    dest: "{{ u.home }}/.config/fish/functions/fish_prompt.fish"
    mode: '0666'
    owner: rocky
    group: rocky
  tags:
    - fish
