---
- name: Initialize the cluster
  ansible.builtin.shell:
    cmd: kubeadm init --ignore-preflight-errors all --config /etc/kubernetes/kubeadm-config.yaml
    chdir: /home/ubuntu

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    mode: "0644"

- name: Wait for kube-system pods become ready
  become: true
  become_user: ubuntu
  ansible.builtin.shell:
    cmd: "kubectl wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=300s"

# https://docs.tigera.io/calico/latest/getting-started/kubernetes/helm
# https://artifacthub.io/packages/helm/projectcalico/tigera-operator
- name: Calico helm install
  become: true
  become_user: ubuntu
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    chart_version: 'v3.29.1'
    release_namespace: tigera-operator
    create_namespace: true
  tags:
    - calico

- name: Wait for calico pods to start
  ansible.builtin.pause:
    seconds: 30
  tags:
    - calico

- name: Wait for calico pods become ready
  become: true
  become_user: ubuntu
  vars:
    calico_namespace: calico-system
  ansible.builtin.shell:
    cmd: "kubectl wait --namespace={{ calico_namespace }} --for=condition=Ready pods --selector k8s-app=calico-node --timeout=300s"
  tags:
    - calico
