---
# https://docs.cilium.io/en/stable/installation/k8s-install-kubeadm/
# https://artifacthub.io/packages/helm/cilium/cilium
- name: Install Cilium helm
  become: true
  become_user: ubuntu
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: '1.17.1' # TODO update to 1.17.2 to patch bug (https://github.com/cilium/cilium/issues/37355) (Only the beta was out ;\)
    release_namespace: kube-system
    values:
      # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubeproxy-free
      kubeProxyReplacement: true
      k8sServiceHost: "{{ ctrl_plane_ip }}"
      k8sServicePort: 6443
      ipam:
        operator:
          clusterPoolIPv4PodCIDRList: ["10.1.0.0/16"]
  tags:
    - cilium

- name: Wait for cilium pods to start
  ansible.builtin.pause:
    seconds: 30
  tags:
    - cilium
