---
- name: Initialize the cluster
  ansible.builtin.shell:
    cmd: kubeadm init --ignore-preflight-errors all --skip-phases addon/kube-proxy --config /etc/kubernetes/kubeadm-config.yaml
    chdir: /home/ubuntu

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    mode: "0644"

- name: Wait for kube-system pods become ready
  become: true
  become_user: ubuntu
  ansible.builtin.shell:
    cmd: "kubectl wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=300s"
