---
- name: Create namespaces
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  loop:
    - monitoring
    - pipeline
    - security
    - web
  tags:
    - code
    - falco
    - longhorn
    - prometheus
    - services
    - teleport
    - website

- name: Install longhorn
  ansible.builtin.include_tasks:
    file: "tasks/k8s/longhorn.yaml"
  tags:
    - services
    - longhorn

- name: Install prometheus
  ansible.builtin.include_tasks:
    file: "tasks/k8s/prometheus.yaml"
  tags:
    - services
    - prometheus

# https://grafana.com/grafana/dashboards/
- name: Grafana dashboards
  ansible.builtin.include_tasks:
    file: "tasks/k8s/grafana.yaml"
  vars:
    dashboards:
      - name: longhorn
        id: 16888
        revision: 9
      - name: traefik
        id: 17346
        revision: 9
      - name: cilium
        id: 21431
        revision: 6
      - name: argocd
        id: 15310
        revision: 3
  loop: "{{ dashboards }}"
  loop_control:
    loop_var: dashboard
  tags:
    - services
    - prometheus

- name: Setup Pipeline
  ansible.builtin.include_tasks:
    file: "tasks/k8s/pipeline.yaml"
  tags:
    - services
    - pipeline

- name: Create website deployment
  ansible.builtin.include_tasks:
    file: "tasks/k8s/website.yaml"
  tags:
    - services
    - website

- name: Setup teleport agent
  ansible.builtin.include_tasks:
    file: "tasks/k8s/teleport.yaml"
  tags:
    - services
    - teleport


- name: Setup code server
  ansible.builtin.include_tasks:
    file: "tasks/k8s/code.yaml"
  tags:
    - code
    - services

# Putting this last to avoid triggers from other services being deployed
- name: Install falco
  ansible.builtin.include_tasks:
    file: "tasks/k8s/falco.yaml"
  tags:
    - services
    - falco
