#SPDX-License-Identifier: MIT-0
---
- name: Include definitions from file
  ansible.builtin.include_vars:
    file: "{{ gpo_definitions }}"
    name: _gpo_definitions

- name: Transfer Required Files to Server
  ansible.windows.win_copy:
    src: "{{ gpo_source }}"
    dest: "{{ gpo_destination }}"

- name: Ensure GPO features are installed
  ansible.windows.win_feature:
    name: GPMC
    state: present

- name: Populate GPOs
  ansible.windows.win_powershell:
    script: "{{ lookup('ansible.builtin.file', 'files/gpo.ps1') }}"
    parameters:
      GPOPath: "{{ gpo_destination }}"
    error_action: stop

- name: Populate Fake GPOs
  ansible.windows.win_powershell:
    script: "{{ lookup('ansible.builtin.file', 'files/fake.ps1') }}"
    parameters:
      GPONames: "{{ _gpo_definitions.fake_names }}"
    error_action: stop
  when: gpo_fake_names == true

- name: Remove Temporary Files from Server
  ansible.windows.win_file:
    path: "{{ gpo_destination }}"
    state: absent