---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recorder
  namespace: pipeline
  labels:
    app.kubernetes.io/name: recorder
secrets:
  - name: influxdb-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pipeline
  name: recorder
  labels:
    app.kubernetes.io/name: recorder
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recorder
  namespace: pipeline
  labels:
    app.kubernetes.io/name: recorder
subjects:
  - kind: ServiceAccount
    name: recorder
    namespace: pipeline
roleRef:
  kind: Role
  name: recorder
  apiGroup: rbac.authorization.k8s.io
