---
- name: Database post configurations
  hosts: database
  become: true
  tasks:
    - name: Update password
      ansible.builtin.user:
        name: admin
        password: "{{ 'example-password' | password_hash('sha512') }}"
